### ISSUE TITLE
how can I train a classifier with my data.

### ISSUE THREAD

**Issue by szm88** [ethz-asl/segmap#66]
@rdube  Hi,rdube. now I have laser data in real environment,and i want to train the model.how can i train a classifier?

**Comment by Durant35** [comment]
+ It seems that there are some `rf_xxx` parameters needed in training step
+ In my opinion, you can do as following
    + [option] Segment to get cloud segments of your desired objects
    + calculate those segments' features using [Eigenvalue-based Features](http://lareg.ensg.ign.fr/labos/matis/pdf/articles_conf/2014/MTSTC3-19-2.pdf) `EigenvalueBasedDescriptor` or Ensemble of Shapes Functions](http://ieeexplore.ieee.org/document/6181760/?arnumber=6181760&tag=1) `EnsembleShapeFunctions`
    + Then you can train the `OpenCvRandomForest`, parameters are needed???
```cpp
void OpenCvRandomForest::train(const Eigen::MatrixXd& features,
                               const Eigen::MatrixXd& labels)
{
...
```

**Comment by rdube** [comment]
Hi guys, Unfortunately I do not have the time to support training a RF for segmatch. I can try to find the parameters that we used for training if you really do need them. 

For your information, we will update segmatch soon and will not be supporting random forests anymore. The issue is that it can be too expensive to use when doing localization in large maps, in comparison to doing k-NN retrieval in feature space. With the upcoming version we can do localization at 10Hz on velodyne data. See our RA-L paper on this strategy here: [incremental localization](http://www.gilitschenski.org/igor/publication/201801-ral-incremental_segmatch/)

We will soon include a new descriptor which might be of interest to you. In the mean-time I would encourage you to use the eigen-value based descriptor with knn retrieval. Update the code and demonstrations soon and will be happy to help you with this if you have any issue. Hope that helps!

**Comment by Durant35** [comment]
Great！Thanks a lot for your kindly replay. I will try your suggestions soon. Hope to feedback.

**Comment by Durant35** [comment]
Awesome！Thanks for your kindly reply.
